# apiVersion: v1
# kind: Namespace
# metadata:
#   name: cnpg-system
#   annotations:
#     linkerd.io/inject: enabled
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: cloudnative-pg-operator
#   namespace: argocd
# spec:
#   project: aks-infrastructure
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: cnpg-system
#   source:
#     repoURL: https://cloudnative-pg.github.io/charts
#     chart: cloudnative-pg
#     targetRevision: 0.17.0
#   # syncPolicy:
#   #   automated: {}