# PROMETHEUS-COMMUNITY
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-prometheus-community
  namespace: argocd
stringData:
  name: prometheus-community
  type: helm
  # project is optional
  project: aks-infrastructure
  url: https://prometheus-community.github.io/helm-charts
---
# INGRESS-NGINX
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-ingress-nginx
  namespace: argocd
stringData:
  name: ingress-nginx
  type: helm
  # project is optional
  project: aks-infrastructure
  url: https://kubernetes.github.io/ingress-nginx
---
# BITNAMI
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-bitnami
  namespace: argocd
stringData:
  name: bitnami
  type: helm
  # project is optional
  project: aks-infrastructure
  url: https://charts.bitnami.com/bitnami
---
# EXTERNAL-SECRETS
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-external-secrets
  namespace: argocd
stringData:
  name: external-secrets
  type: helm
  # project is optional
  project: aks-infrastructure
  url: https://charts.external-secrets.io
---
# CLOUDNATIVEPG
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-cloudnative-pg
  namespace: argocd
stringData:
  name: CloudNativePG
  type: helm
  # project is optional
  project: aks-infrastructure
  url: https://cloudnative-pg.github.io/charts
---
# LOKI
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-loki
  namespace: argocd
stringData:
  name: loki
  type: helm
  # project is optional
  project: aks-infrastructure
  url: https://grafana.github.io/helm-charts